name: build-pr

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ui/
          push: true
          tags: storjstrategy/iris:pr-${{ github.event.number }}

      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            _Good day._
            
            On behalf of her majesty, this pull request has been built and pushed to DockerHub.
            Run it locally using the royal command below.
            
            ```
            docker run --rm --pull always -it -p 3000:80 storjstrategy/iris:pr-${{ github.event.number }}
            ```
            
            Then browse to [http://localhost:3000/](http://localhost:3000) accordingly.

            Sincerely,
            `storjrdbot`
          repo-token: ${{ secrets.BOT_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
          allow-repeats: false
