name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ui/
          push: true
          tags: storjstrategy/iris:commit-${{ steps.vars.outputs.sha_short }}
          
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: ui/
          push: true
          tags: storjstrategy/iris:latest
