name: build-pr

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(jq --raw-output .pull_request.number \"$GITHUB_EVENT_PATH\")"

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ui/
          push: true
          tags: storjstrategy/iris:pr-${{ steps.vars.outputs.sha_short }}

      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            **Hello**
            🌏
            !
          repo-token: ${{ secrets.BOT_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
          allow-repeats: false

      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: ui/
          push: true
          tags: storjstrategy/iris:latest
