name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - run: just test

      - uses: actions/upload-artifact@v2
        with:
          name: ui-tests-output
          path: |
            ui-tests-output/*
