name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

        # Pull docker images before caching
      - run: just test-init

      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - run: IRIS_EMAIL="${{ secrets.IRIS_EMAIL }}" IRIS_PASSWORD="${{ secrets.IRIS_PASSWORD }}" just test

      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: ui-tests-output/*
